services:
  db:
    image: mysql:8.0
    container_name: drs_tim3_25_26-mysql
    environment:
      MYSQL_DATABASE: quiz_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - drs_mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  drs_mysqldata:
