services:
  mysql:
    image: mysql:8.0
    container_name: DRS_quiz
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: USER_DATA
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5002:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./01-user-data.sql:/docker-entrypoint-initdb.d/01-user-data.sql:ro
      - ./02-quizzes-data.sql:/docker-entrypoint-initdb.d/02-quizzes-data.sql:ro
      - ./03-grant-privileges.sql:/docker-entrypoint-initdb.d/03-grant-privileges.sql:ro

volumes:
  mysql_data: